-- ====================================================================
--   SCRIPT COMPLETO GYMBROT
--   Crea/repara toda la BD para que coincida con la app Java
--   1. CREACION DE TABLAS (si no existen)
--   2. ALTER TABLE (ajuste de tamanos + columnas faltantes)
--   3. TIPO AUXILIAR NUMBER_ARRAY
--   4. PAQUETE PKG_GYMBROT (funciones + procedimientos)
--   5. TRIGGERS
--   6. DATOS INICIALES (especialidades, planes)
-- ====================================================================


-- ============================================================
--  1. CREACION DE TABLAS (SOLO SI NO EXISTEN)
-- ============================================================

CREATE TABLE ESPECIALIDADES (
    id_especialidad NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR2(50) NOT NULL
);

CREATE TABLE PLANES_MEMBRESIAS (
    id_plan          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR2(50) NOT NULL,
    descripcion      VARCHAR2(255),
    precio_mensual   NUMBER(10,2),
    precio_semestral NUMBER(10,2),
    precio_anual     NUMBER(10,2),
    beneficios       VARCHAR2(500)
);

CREATE TABLE PLANTILLAS_MENSAJE (
    id_plantilla           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                 VARCHAR2(50) NOT NULL,
    tipo                   VARCHAR2(20),
    asunto                 VARCHAR2(100),
    cuerpo_html            CLOB,
    cuerpo_texto           CLOB,
    variables_disponibles  VARCHAR2(255),
    activa                 NUMBER(1) DEFAULT 1
);

CREATE TABLE USUARIOS (
    numero_identificacion VARCHAR2(20) PRIMARY KEY,
    tipo_identificacion   VARCHAR2(5) NOT NULL,
    nombre                VARCHAR2(50) NOT NULL,
    apellidos             VARCHAR2(50) NOT NULL,
    telefono              VARCHAR2(20),
    correo                VARCHAR2(100),
    contrasena_hash       VARCHAR2(255) NOT NULL,
    foto_url              VARCHAR2(255),
    estado                VARCHAR2(20) DEFAULT 'ACTIVO',
    fecha_registro        DATE DEFAULT SYSDATE,
    tipo_usuario          VARCHAR2(20) NOT NULL
);

CREATE TABLE CLIENTES (
    numero_identificacion VARCHAR2(20) PRIMARY KEY,
    direccion             VARCHAR2(150),
    fecha_nacimiento      DATE,
    huella_dactilar       BLOB,
    CONSTRAINT fk_cliente_usuario
        FOREIGN KEY (numero_identificacion) REFERENCES USUARIOS(numero_identificacion)
);

CREATE TABLE INSTRUCTORES (
    numero_identificacion VARCHAR2(20) PRIMARY KEY,
    id_especialidad       NUMBER,
    disponibilidad        VARCHAR2(100),
    fecha_contratacion    DATE DEFAULT SYSDATE,
    CONSTRAINT fk_instructor_usuario
        FOREIGN KEY (numero_identificacion) REFERENCES USUARIOS(numero_identificacion),
    CONSTRAINT fk_instructor_especialidad
        FOREIGN KEY (id_especialidad) REFERENCES ESPECIALIDADES(id_especialidad)
);

CREATE TABLE ADMINISTRADORES (
    numero_identificacion VARCHAR2(20) PRIMARY KEY,
    rol                   VARCHAR2(50) DEFAULT 'ADMIN',
    CONSTRAINT fk_admin_usuario
        FOREIGN KEY (numero_identificacion) REFERENCES USUARIOS(numero_identificacion)
);

CREATE TABLE MEMBRESIAS (
    id_membresia     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_plan          NUMBER NOT NULL,
    tipo_membresia   VARCHAR2(20),
    modalidad_pago   VARCHAR2(20),
    valor            NUMBER(10,2),
    fecha_inicio     DATE DEFAULT SYSDATE,
    fecha_vencimiento DATE NOT NULL,
    estado           VARCHAR2(20) DEFAULT 'ACTIVA',
    CONSTRAINT fk_membresia_plan
        FOREIGN KEY (id_plan) REFERENCES PLANES_MEMBRESIAS(id_plan)
);

CREATE TABLE HISTORIAL_MEMBRESIAS (
    id_historial     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente       VARCHAR2(20) NOT NULL,
    id_membresia     NUMBER NOT NULL,
    fecha_asignacion DATE DEFAULT SYSDATE,
    fecha_fin        DATE,
    activa           NUMBER(1) DEFAULT 1,
    CONSTRAINT fk_historial_cliente
        FOREIGN KEY (id_cliente) REFERENCES CLIENTES(numero_identificacion),
    CONSTRAINT fk_historial_membresia
        FOREIGN KEY (id_membresia) REFERENCES MEMBRESIAS(id_membresia)
);

CREATE TABLE PAGOS (
    id_pago                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_membresia            NUMBER NOT NULL,
    id_cliente              VARCHAR2(20) NOT NULL,
    fecha_pago              DATE DEFAULT SYSDATE,
    valor                   NUMBER(10,2),
    metodo_pago             VARCHAR2(50),
    estado_pago             VARCHAR2(20),
    referencia_transaccion  VARCHAR2(50),
    observaciones           VARCHAR2(255),
    CONSTRAINT fk_pago_membresia
        FOREIGN KEY (id_membresia) REFERENCES MEMBRESIAS(id_membresia),
    CONSTRAINT fk_pago_cliente
        FOREIGN KEY (id_cliente) REFERENCES CLIENTES(numero_identificacion)
);

CREATE TABLE EJERCICIOS (
    id_ejercicio     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR2(50) NOT NULL,
    descripcion      VARCHAR2(500),
    grupo_muscular   VARCHAR2(50),
    series           NUMBER,
    repeticiones     NUMBER,
    duracion_minutos NUMBER,
    nivel            VARCHAR2(20),
    recurso_url      VARCHAR2(255),
    estado           VARCHAR2(10) DEFAULT 'ACTIVO'
);

CREATE TABLE RUTINAS (
    id_rutina        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_instructor    VARCHAR2(20),
    id_cliente       VARCHAR2(20),
    nombre           VARCHAR2(50) NOT NULL,
    descripcion      VARCHAR2(500),
    fecha_creacion   DATE DEFAULT SYSDATE,
    fecha_fin        DATE,
    dias_semana      VARCHAR2(50),
    objetivo         VARCHAR2(100),
    estado           VARCHAR2(10) DEFAULT 'ACTIVO',
    CONSTRAINT fk_rutina_instructor
        FOREIGN KEY (id_instructor) REFERENCES INSTRUCTORES(numero_identificacion),
    CONSTRAINT fk_rutina_cliente
        FOREIGN KEY (id_cliente) REFERENCES CLIENTES(numero_identificacion)
);

CREATE TABLE RUTINA_EJERCICIOS (
    id_rutina        NUMBER NOT NULL,
    id_ejercicio     NUMBER NOT NULL,
    orden            NUMBER,
    dia_semana       VARCHAR2(20),
    notas_instructor VARCHAR2(500),
    PRIMARY KEY (id_rutina, id_ejercicio),
    CONSTRAINT fk_re_rutina
        FOREIGN KEY (id_rutina) REFERENCES RUTINAS(id_rutina),
    CONSTRAINT fk_re_ejercicio
        FOREIGN KEY (id_ejercicio) REFERENCES EJERCICIOS(id_ejercicio)
);

CREATE TABLE PROGRESOS (
    id_progreso      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente       VARCHAR2(20) NOT NULL,
    fecha_registro   DATE DEFAULT SYSDATE,
    peso             NUMBER(5,2),
    altura           NUMBER(3,2),
    imc              NUMBER(4,2),
    porcentaje_grasa NUMBER(4,1),
    masa_muscular    NUMBER(5,2),
    objetivo         VARCHAR2(100),
    observaciones    VARCHAR2(500),
    estado           VARCHAR2(10) DEFAULT 'ACTIVO',
    CONSTRAINT fk_progreso_cliente
        FOREIGN KEY (id_cliente) REFERENCES CLIENTES(numero_identificacion)
);

CREATE TABLE CITAS (
    id_cita          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_instructor    VARCHAR2(20) NOT NULL,
    id_cliente       VARCHAR2(20) NOT NULL,
    fecha            DATE NOT NULL,
    hora             TIMESTAMP NOT NULL,
    tipo_cita        VARCHAR2(50),
    estado           VARCHAR2(20) DEFAULT 'PENDIENTE',
    notas            VARCHAR2(500),
    CONSTRAINT fk_cita_instructor
        FOREIGN KEY (id_instructor) REFERENCES INSTRUCTORES(numero_identificacion),
    CONSTRAINT fk_cita_cliente
        FOREIGN KEY (id_cliente) REFERENCES CLIENTES(numero_identificacion)
);

CREATE TABLE REGISTROS_INGRESOS (
    id_ingreso          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente          VARCHAR2(20) NOT NULL,
    fecha               DATE DEFAULT SYSDATE,
    hora_entrada        TIMESTAMP DEFAULT SYSTIMESTAMP,
    hora_salida         TIMESTAMP,
    metodo_verificacion VARCHAR2(30),
    estado_verificacion VARCHAR2(20),
    CONSTRAINT fk_ingreso_cliente
        FOREIGN KEY (id_cliente) REFERENCES CLIENTES(numero_identificacion)
);

CREATE TABLE NOTIFICACIONES (
    id_notificacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente      VARCHAR2(20),
    id_plantilla    NUMBER,
    tipo            VARCHAR2(20),
    asunto          VARCHAR2(100),
    contenido       CLOB,
    estado_envio    VARCHAR2(20) DEFAULT 'PENDIENTE',
    fecha_envio     TIMESTAMP DEFAULT SYSTIMESTAMP,
    origen          VARCHAR2(50),
    CONSTRAINT fk_notif_cliente
        FOREIGN KEY (id_cliente) REFERENCES CLIENTES(numero_identificacion),
    CONSTRAINT fk_notif_plantilla
        FOREIGN KEY (id_plantilla) REFERENCES PLANTILLAS_MENSAJE(id_plantilla)
);

CREATE TABLE SESIONES_GYMBROT (
    id_sesion       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente      VARCHAR2(20),
    fecha           DATE DEFAULT SYSDATE,
    hora_inicio     TIMESTAMP DEFAULT SYSTIMESTAMP,
    hora_fin        TIMESTAMP,
    contexto_activo VARCHAR2(50),
    CONSTRAINT fk_ses_cliente
        FOREIGN KEY (id_cliente) REFERENCES CLIENTES(numero_identificacion)
);

CREATE TABLE MENSAJES_GYMBROT (
    id_mensaje      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sesion       NUMBER NOT NULL,
    id_cita         NUMBER,
    remitente       VARCHAR2(20),
    contenido       CLOB,
    timestamp_msg   TIMESTAMP DEFAULT SYSTIMESTAMP,
    tipo_intencion  VARCHAR2(50),
    CONSTRAINT fk_msg_sesion
        FOREIGN KEY (id_sesion) REFERENCES SESIONES_GYMBROT(id_sesion),
    CONSTRAINT fk_msg_cita
        FOREIGN KEY (id_cita) REFERENCES CITAS(id_cita)
);


-- ============================================================
--  2. AJUSTE DE LONGITUDES (VARCHAR2) — tamanos realistas
--     Si las columnas ya existen con tamano mayor, esto falla;
--     se puede comentar cada linea y solo dejar las necesarias.
-- ============================================================

ALTER TABLE ESPECIALIDADES       MODIFY nombre               VARCHAR2(50);
ALTER TABLE PLANES_MEMBRESIAS    MODIFY nombre               VARCHAR2(50);
ALTER TABLE PLANES_MEMBRESIAS    MODIFY descripcion          VARCHAR2(255);
ALTER TABLE PLANTILLAS_MENSAJE   MODIFY nombre               VARCHAR2(50);
ALTER TABLE PLANTILLAS_MENSAJE   MODIFY asunto               VARCHAR2(100);
ALTER TABLE PLANTILLAS_MENSAJE   MODIFY variables_disponibles VARCHAR2(255);
ALTER TABLE EJERCICIOS           MODIFY nombre               VARCHAR2(50);
ALTER TABLE EJERCICIOS           MODIFY grupo_muscular       VARCHAR2(50);
ALTER TABLE EJERCICIOS           MODIFY recurso_url          VARCHAR2(255);
ALTER TABLE USUARIOS             MODIFY nombre               VARCHAR2(50);
ALTER TABLE USUARIOS             MODIFY apellidos            VARCHAR2(50);
ALTER TABLE USUARIOS             MODIFY correo               VARCHAR2(100);
ALTER TABLE USUARIOS             MODIFY foto_url             VARCHAR2(255);
ALTER TABLE CLIENTES             MODIFY direccion            VARCHAR2(150);
ALTER TABLE INSTRUCTORES         MODIFY disponibilidad       VARCHAR2(100);
ALTER TABLE PAGOS                MODIFY referencia_transaccion VARCHAR2(50);
ALTER TABLE PAGOS                MODIFY observaciones        VARCHAR2(255);
ALTER TABLE PROGRESOS            MODIFY objetivo             VARCHAR2(100);
ALTER TABLE RUTINAS              MODIFY nombre               VARCHAR2(50);
ALTER TABLE RUTINAS              MODIFY dias_semana          VARCHAR2(50);
ALTER TABLE RUTINAS              MODIFY objetivo             VARCHAR2(100);
ALTER TABLE NOTIFICACIONES       MODIFY asunto               VARCHAR2(100);


-- ============================================================
--  3. COLUMNAS FALTANTES (ADD)
-- ============================================================

ALTER TABLE RUTINAS ADD (estado VARCHAR2(10) DEFAULT 'ACTIVO');
ALTER TABLE EJERCICIOS ADD (estado VARCHAR2(10) DEFAULT 'ACTIVO');
ALTER TABLE PROGRESOS ADD (estado VARCHAR2(10) DEFAULT 'ACTIVO');


-- ============================================================
--  4. TIPO AUXILIAR
-- ============================================================

CREATE OR REPLACE TYPE NUMBER_ARRAY AS TABLE OF NUMBER;
/


-- ============================================================
--  5. PAQUETE PKG_GYMBROT
-- ============================================================

CREATE OR REPLACE PACKAGE PKG_GYMBROT AS

    -- ● FUNCIONES
    FUNCTION FN_CONTAR_MIEMBROS_ACTIVOS    RETURN NUMBER;
    FUNCTION FN_CONTAR_ACTIVOS_HOY         RETURN NUMBER;
    FUNCTION FN_INGRESOS_MES_ACTUAL        RETURN NUMBER;
    FUNCTION FN_CALCULAR_IMC(p_peso NUMBER, p_altura_mts NUMBER)
        RETURN NUMBER;
    FUNCTION FN_CALCULAR_EDAD(p_fecha_nac DATE) RETURN NUMBER;

    -- ● PROCEDIMIENTOS
    PROCEDURE SP_REGISTRAR_CLIENTE(
        p_id           IN VARCHAR2,
        p_tipo_id      IN VARCHAR2,
        p_nombre       IN VARCHAR2,
        p_apellidos    IN VARCHAR2,
        p_telefono     IN VARCHAR2,
        p_correo       IN VARCHAR2,
        p_contrasena   IN VARCHAR2,
        p_direccion    IN VARCHAR2,
        p_fecha_nac    IN DATE,
        p_huella       IN BLOB DEFAULT NULL,
        p_codigo_out   OUT NUMBER,
        p_mensaje_out  OUT VARCHAR2
    );

    PROCEDURE SP_ACTUALIZAR_CLIENTE(
        p_id           IN VARCHAR2,
        p_nombre       IN VARCHAR2,
        p_apellidos    IN VARCHAR2,
        p_telefono     IN VARCHAR2,
        p_correo       IN VARCHAR2,
        p_direccion    IN VARCHAR2,
        p_fecha_nac    IN DATE,
        p_huella       IN BLOB DEFAULT NULL,
        p_codigo_out   OUT NUMBER,
        p_mensaje_out  OUT VARCHAR2
    );

    PROCEDURE SP_REGISTRAR_INSTRUCTOR(
        p_id              IN VARCHAR2,
        p_tipo_id         IN VARCHAR2,
        p_nombre          IN VARCHAR2,
        p_apellidos       IN VARCHAR2,
        p_telefono        IN VARCHAR2,
        p_correo          IN VARCHAR2,
        p_contrasena      IN VARCHAR2,
        p_id_especialidad IN NUMBER,
        p_disponibilidad  IN VARCHAR2,
        p_codigo_out      OUT NUMBER,
        p_mensaje_out     OUT VARCHAR2
    );

    PROCEDURE SP_ACTUALIZAR_INSTRUCTOR(
        p_id              IN VARCHAR2,
        p_nombre          IN VARCHAR2,
        p_apellidos       IN VARCHAR2,
        p_telefono        IN VARCHAR2,
        p_correo          IN VARCHAR2,
        p_id_especialidad IN NUMBER,
        p_disponibilidad  IN VARCHAR2,
        p_codigo_out      OUT NUMBER,
        p_mensaje_out     OUT VARCHAR2
    );

    PROCEDURE SP_RENOVAR_MEMBRESIA(
        p_id_cliente      IN VARCHAR2,
        p_id_plan         IN NUMBER,
        p_modalidad       IN VARCHAR2,
        p_metodo_pago     IN VARCHAR2,
        p_valor           IN NUMBER,
        p_codigo_out      OUT NUMBER,
        p_mensaje_out     OUT VARCHAR2
    );

    PROCEDURE SP_REGISTRAR_PROGRESO(
        p_id_cliente      IN VARCHAR2,
        p_peso            IN NUMBER,
        p_altura          IN NUMBER,
        p_porc_grasa      IN NUMBER DEFAULT NULL,
        p_masa_muscular   IN NUMBER DEFAULT NULL,
        p_objetivo        IN VARCHAR2 DEFAULT NULL,
        p_observaciones   IN VARCHAR2 DEFAULT NULL,
        p_codigo_out      OUT NUMBER,
        p_mensaje_out     OUT VARCHAR2
    );

    PROCEDURE SP_CREAR_EJERCICIO(
        p_nombre          IN VARCHAR2,
        p_descripcion     IN VARCHAR2 DEFAULT NULL,
        p_grupo_muscular  IN VARCHAR2 DEFAULT NULL,
        p_series          IN NUMBER DEFAULT NULL,
        p_repeticiones    IN NUMBER DEFAULT NULL,
        p_duracion        IN NUMBER DEFAULT NULL,
        p_nivel           IN VARCHAR2 DEFAULT NULL,
        p_recurso_url     IN VARCHAR2 DEFAULT NULL,
        p_codigo_out      OUT NUMBER,
        p_mensaje_out     OUT VARCHAR2
    );

    PROCEDURE SP_ACTUALIZAR_EJERCICIO(
        p_id_ejercicio    IN NUMBER,
        p_nombre          IN VARCHAR2,
        p_descripcion     IN VARCHAR2 DEFAULT NULL,
        p_grupo_muscular  IN VARCHAR2 DEFAULT NULL,
        p_series          IN NUMBER DEFAULT NULL,
        p_repeticiones    IN NUMBER DEFAULT NULL,
        p_duracion        IN NUMBER DEFAULT NULL,
        p_nivel           IN VARCHAR2 DEFAULT NULL,
        p_recurso_url     IN VARCHAR2 DEFAULT NULL,
        p_codigo_out      OUT NUMBER,
        p_mensaje_out     OUT VARCHAR2
    );

    PROCEDURE SP_AGENDAR_CITA(
        p_id_instructor   IN VARCHAR2,
        p_id_cliente      IN VARCHAR2,
        p_fecha           IN DATE,
        p_hora            IN TIMESTAMP,
        p_tipo_cita       IN VARCHAR2,
        p_notas           IN VARCHAR2 DEFAULT NULL,
        p_codigo_out      OUT NUMBER,
        p_mensaje_out     OUT VARCHAR2
    );

    PROCEDURE SP_CANCELAR_CITA(
        p_id_cita         IN NUMBER,
        p_codigo_out      OUT NUMBER,
        p_mensaje_out     OUT VARCHAR2
    );

    PROCEDURE SP_CREAR_RUTINA_COMPLETA(
        p_id_instructor   IN VARCHAR2,
        p_id_cliente      IN VARCHAR2,
        p_nombre          IN VARCHAR2,
        p_descripcion     IN VARCHAR2 DEFAULT NULL,
        p_fecha_fin       IN DATE DEFAULT NULL,
        p_dias_semana     IN VARCHAR2 DEFAULT NULL,
        p_objetivo        IN VARCHAR2 DEFAULT NULL,
        p_ejercicios      IN NUMBER_ARRAY DEFAULT NULL,
        p_codigo_out      OUT NUMBER,
        p_mensaje_out     OUT VARCHAR2
    );

    PROCEDURE SP_REGISTRAR_INGRESO(
        p_id_cliente          IN VARCHAR2,
        p_metodo_verificacion IN VARCHAR2 DEFAULT 'HUELLA',
        p_codigo_out          OUT NUMBER,
        p_mensaje_out         OUT VARCHAR2
    );

    PROCEDURE SP_REGISTRAR_SALIDA(
        p_id_cliente      IN VARCHAR2,
        p_codigo_out      OUT NUMBER,
        p_mensaje_out     OUT VARCHAR2
    );

END PKG_GYMBROT;
/


CREATE OR REPLACE PACKAGE BODY PKG_GYMBROT AS

    -- ═════════════════════════════════════════════════════════
    --  FUNCIONES
    -- ═════════════════════════════════════════════════════════

    FUNCTION FN_CONTAR_MIEMBROS_ACTIVOS RETURN NUMBER IS
        v_total NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_total
        FROM USUARIOS
        WHERE tipo_usuario = 'CLIENTE' AND estado = 'ACTIVO';
        RETURN v_total;
    END FN_CONTAR_MIEMBROS_ACTIVOS;


    FUNCTION FN_CONTAR_ACTIVOS_HOY RETURN NUMBER IS
        v_total NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_total
        FROM REGISTROS_INGRESOS
        WHERE fecha = TRUNC(SYSDATE) AND hora_salida IS NULL;
        RETURN v_total;
    END FN_CONTAR_ACTIVOS_HOY;


    FUNCTION FN_INGRESOS_MES_ACTUAL RETURN NUMBER IS
        v_total NUMBER;
    BEGIN
        SELECT NVL(SUM(valor), 0) INTO v_total
        FROM PAGOS
        WHERE EXTRACT(MONTH FROM fecha_pago) = EXTRACT(MONTH FROM SYSDATE)
          AND EXTRACT(YEAR  FROM fecha_pago) = EXTRACT(YEAR  FROM SYSDATE)
          AND estado_pago = 'EXITOSO';
        RETURN v_total;
    END FN_INGRESOS_MES_ACTUAL;


    FUNCTION FN_CALCULAR_IMC(
        p_peso       NUMBER,
        p_altura_mts NUMBER
    ) RETURN NUMBER IS
    BEGIN
        IF p_altura_mts IS NULL OR p_altura_mts <= 0 THEN
            RETURN NULL;
        END IF;
        RETURN ROUND(p_peso / (p_altura_mts * p_altura_mts), 2);
    END FN_CALCULAR_IMC;


    FUNCTION FN_CALCULAR_EDAD(p_fecha_nac DATE) RETURN NUMBER IS
    BEGIN
        RETURN TRUNC(MONTHS_BETWEEN(SYSDATE, p_fecha_nac) / 12);
    END FN_CALCULAR_EDAD;


    -- ═════════════════════════════════════════════════════════
    --  PROCEDIMIENTOS
    -- ═════════════════════════════════════════════════════════

    PROCEDURE SP_REGISTRAR_CLIENTE(
        p_id           IN VARCHAR2,
        p_tipo_id      IN VARCHAR2,
        p_nombre       IN VARCHAR2,
        p_apellidos    IN VARCHAR2,
        p_telefono     IN VARCHAR2,
        p_correo       IN VARCHAR2,
        p_contrasena   IN VARCHAR2,
        p_direccion    IN VARCHAR2,
        p_fecha_nac    IN DATE,
        p_huella       IN BLOB DEFAULT NULL,
        p_codigo_out   OUT NUMBER,
        p_mensaje_out  OUT VARCHAR2
    ) IS
        PRAGMA AUTONOMOUS_TRANSACTION;
    BEGIN
        BEGIN
            SELECT 1 INTO p_codigo_out FROM USUARIOS
            WHERE numero_identificacion = p_id AND ROWNUM = 1;
            p_codigo_out  := 0;
            p_mensaje_out := 'Ya existe un usuario con esa identificacion.';
            RETURN;
        EXCEPTION WHEN NO_DATA_FOUND THEN NULL;
        END;

        INSERT INTO USUARIOS (
            numero_identificacion, tipo_identificacion, nombre, apellidos,
            telefono, correo, contrasena_hash, estado, fecha_registro, tipo_usuario
        ) VALUES (
            p_id, p_tipo_id, p_nombre, p_apellidos,
            p_telefono, p_correo, p_contrasena, 'ACTIVO', SYSDATE, 'CLIENTE'
        );

        INSERT INTO CLIENTES (
            numero_identificacion, direccion, fecha_nacimiento, huella_dactilar
        ) VALUES (
            p_id, p_direccion, p_fecha_nac, p_huella
        );

        COMMIT;
        p_codigo_out  := 1;
        p_mensaje_out := 'Cliente registrado exitosamente.';

    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            p_codigo_out  := -1;
            p_mensaje_out := 'Error: ' || SQLERRM;
    END SP_REGISTRAR_CLIENTE;


    PROCEDURE SP_ACTUALIZAR_CLIENTE(
        p_id           IN VARCHAR2,
        p_nombre       IN VARCHAR2,
        p_apellidos    IN VARCHAR2,
        p_telefono     IN VARCHAR2,
        p_correo       IN VARCHAR2,
        p_direccion    IN VARCHAR2,
        p_fecha_nac    IN DATE,
        p_huella       IN BLOB DEFAULT NULL,
        p_codigo_out   OUT NUMBER,
        p_mensaje_out  OUT VARCHAR2
    ) IS
        PRAGMA AUTONOMOUS_TRANSACTION;
    BEGIN
        UPDATE USUARIOS SET
            nombre     = p_nombre,
            apellidos  = p_apellidos,
            telefono   = p_telefono,
            correo     = p_correo
        WHERE numero_identificacion = p_id;

        IF SQL%ROWCOUNT = 0 THEN
            p_codigo_out  := 0;
            p_mensaje_out := 'Cliente no encontrado.';
            RETURN;
        END IF;

        UPDATE CLIENTES SET
            direccion        = p_direccion,
            fecha_nacimiento = p_fecha_nac,
            huella_dactilar  = NVL(p_huella, huella_dactilar)
        WHERE numero_identificacion = p_id;

        COMMIT;
        p_codigo_out  := 1;
        p_mensaje_out := 'Cliente actualizado exitosamente.';

    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            p_codigo_out  := -1;
            p_mensaje_out := 'Error: ' || SQLERRM;
    END SP_ACTUALIZAR_CLIENTE;


    PROCEDURE SP_REGISTRAR_INSTRUCTOR(
        p_id              IN VARCHAR2,
        p_tipo_id         IN VARCHAR2,
        p_nombre          IN VARCHAR2,
        p_apellidos       IN VARCHAR2,
        p_telefono        IN VARCHAR2,
        p_correo          IN VARCHAR2,
        p_contrasena      IN VARCHAR2,
        p_id_especialidad IN NUMBER,
        p_disponibilidad  IN VARCHAR2,
        p_codigo_out      OUT NUMBER,
        p_mensaje_out     OUT VARCHAR2
    ) IS
        PRAGMA AUTONOMOUS_TRANSACTION;
    BEGIN
        BEGIN
            SELECT 1 INTO p_codigo_out FROM USUARIOS
            WHERE numero_identificacion = p_id AND ROWNUM = 1;
            p_codigo_out  := 0;
            p_mensaje_out := 'Ya existe un usuario con esa identificacion.';
            RETURN;
        EXCEPTION WHEN NO_DATA_FOUND THEN NULL;
        END;

        INSERT INTO USUARIOS (
            numero_identificacion, tipo_identificacion, nombre, apellidos,
            telefono, correo, contrasena_hash, estado, fecha_registro, tipo_usuario
        ) VALUES (
            p_id, p_tipo_id, p_nombre, p_apellidos,
            p_telefono, p_correo, p_contrasena, 'ACTIVO', SYSDATE, 'INSTRUCTOR'
        );

        INSERT INTO INSTRUCTORES (numero_identificacion, id_especialidad, disponibilidad, fecha_contratacion)
        VALUES (p_id, p_id_especialidad, p_disponibilidad, SYSDATE);

        COMMIT;
        p_codigo_out  := 1;
        p_mensaje_out := 'Instructor registrado exitosamente.';

    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            p_codigo_out  := -1;
            p_mensaje_out := 'Error: ' || SQLERRM;
    END SP_REGISTRAR_INSTRUCTOR;


    PROCEDURE SP_ACTUALIZAR_INSTRUCTOR(
        p_id              IN VARCHAR2,
        p_nombre          IN VARCHAR2,
        p_apellidos       IN VARCHAR2,
        p_telefono        IN VARCHAR2,
        p_correo          IN VARCHAR2,
        p_id_especialidad IN NUMBER,
        p_disponibilidad  IN VARCHAR2,
        p_codigo_out      OUT NUMBER,
        p_mensaje_out     OUT VARCHAR2
    ) IS
        PRAGMA AUTONOMOUS_TRANSACTION;
    BEGIN
        UPDATE USUARIOS SET
            nombre    = p_nombre,
            apellidos = p_apellidos,
            telefono  = p_telefono,
            correo    = p_correo
        WHERE numero_identificacion = p_id
          AND tipo_usuario = 'INSTRUCTOR';

        IF SQL%ROWCOUNT = 0 THEN
            p_codigo_out  := 0;
            p_mensaje_out := 'Instructor no encontrado.';
            RETURN;
        END IF;

        UPDATE INSTRUCTORES SET
            id_especialidad = p_id_especialidad,
            disponibilidad  = p_disponibilidad
        WHERE numero_identificacion = p_id;

        COMMIT;
        p_codigo_out  := 1;
        p_mensaje_out := 'Instructor actualizado exitosamente.';

    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            p_codigo_out  := -1;
            p_mensaje_out := 'Error: ' || SQLERRM;
    END SP_ACTUALIZAR_INSTRUCTOR;


    PROCEDURE SP_RENOVAR_MEMBRESIA(
        p_id_cliente      IN VARCHAR2,
        p_id_plan         IN NUMBER,
        p_modalidad       IN VARCHAR2,
        p_metodo_pago     IN VARCHAR2,
        p_valor           IN NUMBER,
        p_codigo_out      OUT NUMBER,
        p_mensaje_out     OUT VARCHAR2
    ) IS
        v_id_membresia    NUMBER;
        v_fecha_venc      DATE;
        v_precio_plan     NUMBER(10,2);
        PRAGMA AUTONOMOUS_TRANSACTION;
    BEGIN
        BEGIN
            SELECT 1 INTO p_codigo_out FROM CLIENTES
            WHERE numero_identificacion = p_id_cliente AND ROWNUM = 1;
        EXCEPTION WHEN NO_DATA_FOUND THEN
            p_codigo_out  := 0;
            p_mensaje_out := 'Cliente no encontrado.';
            RETURN;
        END;

        BEGIN
            SELECT precio_mensual INTO v_precio_plan
            FROM PLANES_MEMBRESIAS WHERE id_plan = p_id_plan;
        EXCEPTION WHEN NO_DATA_FOUND THEN
            p_codigo_out  := 0;
            p_mensaje_out := 'Plan no encontrado.';
            RETURN;
        END;

        v_fecha_venc := CASE p_modalidad
            WHEN 'MENSUAL'   THEN ADD_MONTHS(TRUNC(SYSDATE), 1)
            WHEN 'SEMESTRAL' THEN ADD_MONTHS(TRUNC(SYSDATE), 6)
            WHEN 'ANUAL'     THEN ADD_MONTHS(TRUNC(SYSDATE), 12)
            ELSE ADD_MONTHS(TRUNC(SYSDATE), 1)
        END;

        INSERT INTO MEMBRESIAS (id_plan, tipo_membresia, modalidad_pago, valor, fecha_inicio, fecha_vencimiento, estado)
        VALUES (p_id_plan, p_modalidad, p_modalidad, p_valor, TRUNC(SYSDATE), v_fecha_venc, 'ACTIVA')
        RETURNING id_membresia INTO v_id_membresia;

        UPDATE HISTORIAL_MEMBRESIAS
        SET activa = 0, fecha_fin = SYSDATE
        WHERE id_cliente = p_id_cliente AND activa = 1;

        INSERT INTO HISTORIAL_MEMBRESIAS (id_cliente, id_membresia, fecha_asignacion, activa)
        VALUES (p_id_cliente, v_id_membresia, SYSDATE, 1);

        INSERT INTO PAGOS (id_membresia, id_cliente, fecha_pago, valor, metodo_pago, estado_pago)
        VALUES (v_id_membresia, p_id_cliente, SYSDATE, p_valor, p_metodo_pago, 'EXITOSO');

        COMMIT;
        p_codigo_out  := 1;
        p_mensaje_out := 'Membresia renovada exitosamente. Vence: ' ||
                         TO_CHAR(v_fecha_venc, 'DD/MM/YYYY');

    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            p_codigo_out  := -1;
            p_mensaje_out := 'Error: ' || SQLERRM;
    END SP_RENOVAR_MEMBRESIA;


    PROCEDURE SP_REGISTRAR_PROGRESO(
        p_id_cliente      IN VARCHAR2,
        p_peso            IN NUMBER,
        p_altura          IN NUMBER,
        p_porc_grasa      IN NUMBER DEFAULT NULL,
        p_masa_muscular   IN NUMBER DEFAULT NULL,
        p_objetivo        IN VARCHAR2 DEFAULT NULL,
        p_observaciones   IN VARCHAR2 DEFAULT NULL,
        p_codigo_out      OUT NUMBER,
        p_mensaje_out     OUT VARCHAR2
    ) IS
    BEGIN
        BEGIN
            SELECT 1 INTO p_codigo_out FROM CLIENTES
            WHERE numero_identificacion = p_id_cliente AND ROWNUM = 1;
        EXCEPTION WHEN NO_DATA_FOUND THEN
            p_codigo_out  := 0;
            p_mensaje_out := 'Cliente no encontrado.';
            RETURN;
        END;

        INSERT INTO PROGRESOS (
            id_cliente, fecha_registro, peso, altura,
            porcentaje_grasa, masa_muscular, objetivo, observaciones
        ) VALUES (
            p_id_cliente, SYSDATE, p_peso, p_altura,
            p_porc_grasa, p_masa_muscular, p_objetivo, p_observaciones
        );

        p_codigo_out  := 1;
        p_mensaje_out := 'Progreso registrado exitosamente.';

    EXCEPTION
        WHEN OTHERS THEN
            p_codigo_out  := -1;
            p_mensaje_out := 'Error: ' || SQLERRM;
    END SP_REGISTRAR_PROGRESO;


    PROCEDURE SP_CREAR_EJERCICIO(
        p_nombre          IN VARCHAR2,
        p_descripcion     IN VARCHAR2 DEFAULT NULL,
        p_grupo_muscular  IN VARCHAR2 DEFAULT NULL,
        p_series          IN NUMBER DEFAULT NULL,
        p_repeticiones    IN NUMBER DEFAULT NULL,
        p_duracion        IN NUMBER DEFAULT NULL,
        p_nivel           IN VARCHAR2 DEFAULT NULL,
        p_recurso_url     IN VARCHAR2 DEFAULT NULL,
        p_codigo_out      OUT NUMBER,
        p_mensaje_out     OUT VARCHAR2
    ) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count
        FROM EJERCICIOS WHERE LOWER(nombre) = LOWER(p_nombre);

        IF v_count > 0 THEN
            p_codigo_out  := 0;
            p_mensaje_out := 'Ya existe un ejercicio con ese nombre.';
            RETURN;
        END IF;

        INSERT INTO EJERCICIOS (
            nombre, descripcion, grupo_muscular, series, repeticiones,
            duracion_minutos, nivel, recurso_url
        ) VALUES (
            p_nombre, p_descripcion, p_grupo_muscular, p_series, p_repeticiones,
            p_duracion, p_nivel, p_recurso_url
        );

        p_codigo_out  := 1;
        p_mensaje_out := 'Ejercicio creado exitosamente.';

    EXCEPTION
        WHEN OTHERS THEN
            p_codigo_out  := -1;
            p_mensaje_out := 'Error: ' || SQLERRM;
    END SP_CREAR_EJERCICIO;


    PROCEDURE SP_ACTUALIZAR_EJERCICIO(
        p_id_ejercicio    IN NUMBER,
        p_nombre          IN VARCHAR2,
        p_descripcion     IN VARCHAR2 DEFAULT NULL,
        p_grupo_muscular  IN VARCHAR2 DEFAULT NULL,
        p_series          IN NUMBER DEFAULT NULL,
        p_repeticiones    IN NUMBER DEFAULT NULL,
        p_duracion        IN NUMBER DEFAULT NULL,
        p_nivel           IN VARCHAR2 DEFAULT NULL,
        p_recurso_url     IN VARCHAR2 DEFAULT NULL,
        p_codigo_out      OUT NUMBER,
        p_mensaje_out     OUT VARCHAR2
    ) IS
    BEGIN
        UPDATE EJERCICIOS SET
            nombre          = p_nombre,
            descripcion     = p_descripcion,
            grupo_muscular  = p_grupo_muscular,
            series          = p_series,
            repeticiones    = p_repeticiones,
            duracion_minutos = p_duracion,
            nivel           = p_nivel,
            recurso_url     = p_recurso_url
        WHERE id_ejercicio = p_id_ejercicio;

        IF SQL%ROWCOUNT = 0 THEN
            p_codigo_out  := 0;
            p_mensaje_out := 'Ejercicio no encontrado.';
        ELSE
            p_codigo_out  := 1;
            p_mensaje_out := 'Ejercicio actualizado exitosamente.';
        END IF;

    EXCEPTION
        WHEN OTHERS THEN
            p_codigo_out  := -1;
            p_mensaje_out := 'Error: ' || SQLERRM;
    END SP_ACTUALIZAR_EJERCICIO;


    PROCEDURE SP_AGENDAR_CITA(
        p_id_instructor   IN VARCHAR2,
        p_id_cliente      IN VARCHAR2,
        p_fecha           IN DATE,
        p_hora            IN TIMESTAMP,
        p_tipo_cita       IN VARCHAR2,
        p_notas           IN VARCHAR2 DEFAULT NULL,
        p_codigo_out      OUT NUMBER,
        p_mensaje_out     OUT VARCHAR2
    ) IS
        v_count  NUMBER;
    BEGIN
        IF p_fecha <= TRUNC(SYSDATE) THEN
            p_codigo_out  := 0;
            p_mensaje_out := 'La fecha debe ser posterior a hoy.';
            RETURN;
        END IF;

        SELECT COUNT(*) INTO v_count
        FROM CITAS
        WHERE id_instructor = p_id_instructor
          AND fecha = p_fecha
          AND hora = p_hora
          AND estado NOT IN ('CANCELADA', 'COMPLETADA');

        IF v_count > 0 THEN
            p_codigo_out  := 0;
            p_mensaje_out := 'El instructor ya tiene una cita en ese horario.';
            RETURN;
        END IF;

        SELECT COUNT(*) INTO v_count
        FROM CITAS
        WHERE id_cliente = p_id_cliente
          AND fecha = p_fecha
          AND estado NOT IN ('CANCELADA', 'COMPLETADA');

        IF v_count >= 3 THEN
            p_codigo_out  := 0;
            p_mensaje_out := 'El cliente ya tiene 3 citas programadas para este dia.';
            RETURN;
        END IF;

        INSERT INTO CITAS (id_instructor, id_cliente, fecha, hora, tipo_cita, estado, notas)
        VALUES (p_id_instructor, p_id_cliente, p_fecha, p_hora, p_tipo_cita, 'PENDIENTE', p_notas);

        p_codigo_out  := 1;
        p_mensaje_out := 'Cita agendada exitosamente.';

    EXCEPTION
        WHEN OTHERS THEN
            p_codigo_out  := -1;
            p_mensaje_out := 'Error: ' || SQLERRM;
    END SP_AGENDAR_CITA;


    PROCEDURE SP_CANCELAR_CITA(
        p_id_cita         IN NUMBER,
        p_codigo_out      OUT NUMBER,
        p_mensaje_out     OUT VARCHAR2
    ) IS
        v_id_cliente VARCHAR2(20);
        v_fecha      DATE;
    BEGIN
        SELECT id_cliente, fecha INTO v_id_cliente, v_fecha
        FROM CITAS WHERE id_cita = p_id_cita;

        UPDATE CITAS SET estado = 'CANCELADA'
        WHERE id_cita = p_id_cita AND estado = 'PENDIENTE';

        IF SQL%ROWCOUNT = 0 THEN
            p_codigo_out  := 0;
            p_mensaje_out := 'No se pudo cancelar. La cita no existe o no esta pendiente.';
            RETURN;
        END IF;

        INSERT INTO NOTIFICACIONES (id_cliente, tipo, asunto, contenido, estado_envio, origen)
        VALUES (
            v_id_cliente, 'EMAIL', 'Cita cancelada - GYMBROT',
            'Tu cita #' || p_id_cita || ' del ' ||
            TO_CHAR(v_fecha, 'DD/MM/YYYY') || ' ha sido cancelada.',
            'PENDIENTE', 'SISTEMA'
        );

        p_codigo_out  := 1;
        p_mensaje_out := 'Cita cancelada y notificacion generada.';

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            p_codigo_out  := 0;
            p_mensaje_out := 'Cita no encontrada.';
        WHEN OTHERS THEN
            p_codigo_out  := -1;
            p_mensaje_out := 'Error: ' || SQLERRM;
    END SP_CANCELAR_CITA;


    PROCEDURE SP_CREAR_RUTINA_COMPLETA(
        p_id_instructor   IN VARCHAR2,
        p_id_cliente      IN VARCHAR2,
        p_nombre          IN VARCHAR2,
        p_descripcion     IN VARCHAR2 DEFAULT NULL,
        p_fecha_fin       IN DATE DEFAULT NULL,
        p_dias_semana     IN VARCHAR2 DEFAULT NULL,
        p_objetivo        IN VARCHAR2 DEFAULT NULL,
        p_ejercicios      IN NUMBER_ARRAY DEFAULT NULL,
        p_codigo_out      OUT NUMBER,
        p_mensaje_out     OUT VARCHAR2
    ) IS
        v_id_rutina NUMBER;
        PRAGMA AUTONOMOUS_TRANSACTION;
    BEGIN
        INSERT INTO RUTINAS (id_instructor, id_cliente, nombre, descripcion, fecha_creacion, fecha_fin, dias_semana, objetivo)
        VALUES (p_id_instructor, p_id_cliente, p_nombre, p_descripcion, SYSDATE, p_fecha_fin, p_dias_semana, p_objetivo)
        RETURNING id_rutina INTO v_id_rutina;

        IF p_ejercicios IS NOT NULL THEN
            FOR i IN 1 .. p_ejercicios.COUNT LOOP
                INSERT INTO RUTINA_EJERCICIOS (id_rutina, id_ejercicio, orden)
                VALUES (v_id_rutina, p_ejercicios(i), i);
            END LOOP;
        END IF;

        COMMIT;
        p_codigo_out  := 1;
        p_mensaje_out := 'Rutina creada exitosamente con ID ' || v_id_rutina;

    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            p_codigo_out  := -1;
            p_mensaje_out := 'Error: ' || SQLERRM;
    END SP_CREAR_RUTINA_COMPLETA;


    PROCEDURE SP_REGISTRAR_INGRESO(
        p_id_cliente          IN VARCHAR2,
        p_metodo_verificacion IN VARCHAR2 DEFAULT 'HUELLA',
        p_codigo_out          OUT NUMBER,
        p_mensaje_out         OUT VARCHAR2
    ) IS
        v_activa     NUMBER;
        v_fecha_venc DATE;
    BEGIN
        BEGIN
            SELECT hm.activa, m.fecha_vencimiento
            INTO v_activa, v_fecha_venc
            FROM HISTORIAL_MEMBRESIAS hm
            JOIN MEMBRESIAS m ON hm.id_membresia = m.id_membresia
            WHERE hm.id_cliente = p_id_cliente
              AND hm.activa = 1
              AND ROWNUM = 1;
        EXCEPTION WHEN NO_DATA_FOUND THEN
            p_codigo_out  := 0;
            p_mensaje_out := 'Acceso denegado: sin membresia activa.';
            RETURN;
        END;

        IF v_fecha_venc < TRUNC(SYSDATE) THEN
            p_codigo_out  := 0;
            p_mensaje_out := 'Acceso denegado: membresia vencida desde ' ||
                             TO_CHAR(v_fecha_venc, 'DD/MM/YYYY');
            RETURN;
        END IF;

        UPDATE REGISTROS_INGRESOS
        SET hora_salida = SYSTIMESTAMP
        WHERE id_cliente = p_id_cliente
          AND fecha = TRUNC(SYSDATE)
          AND hora_salida IS NULL;

        INSERT INTO REGISTROS_INGRESOS (id_cliente, fecha, hora_entrada, metodo_verificacion, estado_verificacion)
        VALUES (p_id_cliente, TRUNC(SYSDATE), SYSTIMESTAMP, p_metodo_verificacion, 'APROBADO');

        p_codigo_out  := 1;
        p_mensaje_out := 'Ingreso registrado correctamente.';

    EXCEPTION
        WHEN OTHERS THEN
            p_codigo_out  := -1;
            p_mensaje_out := 'Error: ' || SQLERRM;
    END SP_REGISTRAR_INGRESO;


    PROCEDURE SP_REGISTRAR_SALIDA(
        p_id_cliente      IN VARCHAR2,
        p_codigo_out      OUT NUMBER,
        p_mensaje_out     OUT VARCHAR2
    ) IS
    BEGIN
        UPDATE REGISTROS_INGRESOS
        SET hora_salida = SYSTIMESTAMP
        WHERE id_cliente = p_id_cliente
          AND fecha = TRUNC(SYSDATE)
          AND hora_salida IS NULL;

        IF SQL%ROWCOUNT = 0 THEN
            p_codigo_out  := 0;
            p_mensaje_out := 'No hay ingreso abierto para este cliente.';
        ELSE
            p_codigo_out  := 1;
            p_mensaje_out := 'Salida registrada correctamente.';
        END IF;

    EXCEPTION
        WHEN OTHERS THEN
            p_codigo_out  := -1;
            p_mensaje_out := 'Error: ' || SQLERRM;
    END SP_REGISTRAR_SALIDA;

END PKG_GYMBROT;
/


-- ============================================================
--  6. TRIGGERS
-- ============================================================


-- ● Actualiza estado de membresia a ACTIVA tras pago exitoso
CREATE OR REPLACE TRIGGER TRG_ACTUALIZAR_ESTADO_MEMBRESIA
AFTER INSERT ON PAGOS
FOR EACH ROW
WHEN (NEW.estado_pago = 'EXITOSO')
BEGIN
    UPDATE MEMBRESIAS
    SET estado = 'ACTIVA'
    WHERE id_membresia = :NEW.id_membresia
      AND estado != 'ACTIVA';
END;
/


-- ● Verifica vencimiento al insertar/actualizar membresia
CREATE OR REPLACE TRIGGER TRG_VERIFICAR_VENCIMIENTO_MEMBRESIA
BEFORE INSERT OR UPDATE ON MEMBRESIAS
FOR EACH ROW
BEGIN
    IF :NEW.fecha_vencimiento < TRUNC(SYSDATE) THEN
        :NEW.estado := 'VENCIDA';
    END IF;
END;
/


-- ● Cierra automaticamente ingreso anterior al registrar uno nuevo
CREATE OR REPLACE TRIGGER TRG_REGISTRAR_SALIDA_AUTOMATICA
BEFORE INSERT ON REGISTROS_INGRESOS
FOR EACH ROW
DECLARE
    v_id_ingreso_abierto NUMBER;
BEGIN
    BEGIN
        SELECT id_ingreso INTO v_id_ingreso_abierto
        FROM REGISTROS_INGRESOS
        WHERE id_cliente = :NEW.id_cliente
          AND fecha = TRUNC(SYSDATE)
          AND hora_salida IS NULL
          AND ROWNUM = 1;

        UPDATE REGISTROS_INGRESOS
        SET hora_salida = SYSTIMESTAMP
        WHERE id_ingreso = v_id_ingreso_abierto;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN NULL;
    END;
END;
/


-- ● Desactiva historial anterior al asignar nueva membresia
CREATE OR REPLACE TRIGGER TRG_DESACTIVAR_MEMBRESIA_ANTERIOR
AFTER INSERT ON HISTORIAL_MEMBRESIAS
FOR EACH ROW
BEGIN
    UPDATE HISTORIAL_MEMBRESIAS
    SET activa = 0, fecha_fin = SYSDATE
    WHERE id_cliente = :NEW.id_cliente
      AND id_historial <> :NEW.id_historial
      AND activa = 1;
END;
/


-- ● Crea notificacion automatica al cancelar cita
CREATE OR REPLACE TRIGGER TRG_NOTIFICAR_CANCELACION_CITA
AFTER UPDATE ON CITAS
FOR EACH ROW
WHEN (NEW.estado = 'CANCELADA' AND OLD.estado = 'PENDIENTE')
BEGIN
    INSERT INTO NOTIFICACIONES (id_cliente, tipo, asunto, contenido, estado_envio, origen)
    VALUES (
        :NEW.id_cliente,
        'EMAIL',
        'Cita cancelada - GYMBROT',
        'Tu cita #' || :NEW.id_cita || ' del ' ||
        TO_CHAR(:NEW.fecha, 'DD/MM/YYYY') || ' ha sido cancelada.',
        'PENDIENTE',
        'SISTEMA'
    );
END;
/


-- ● Calcula IMC automaticamente si no se proporciono
CREATE OR REPLACE TRIGGER TRG_PROGRESOS_BI
BEFORE INSERT ON PROGRESOS
FOR EACH ROW
BEGIN
    IF :NEW.imc IS NULL AND :NEW.peso IS NOT NULL
       AND :NEW.altura IS NOT NULL AND :NEW.altura > 0 THEN
        :NEW.imc := ROUND(PKG_GYMBROT.FN_CALCULAR_IMC(:NEW.peso, :NEW.altura), 2);
    END IF;
END;
/


-- ● Protege borrado de ejercicios asignados a rutinas
CREATE OR REPLACE TRIGGER TRG_EJERCICIOS_BD
BEFORE DELETE ON EJERCICIOS
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM RUTINA_EJERCICIOS WHERE id_ejercicio = :OLD.id_ejercicio;

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001,
            'No se puede eliminar el ejercicio: esta asignado a ' ||
            v_count || ' rutina(s).');
    END IF;
END;
/


-- ● Protege borrado de especialidades con instructores asignados
CREATE OR REPLACE TRIGGER TRG_ESPECIALIDADES_BD
BEFORE DELETE ON ESPECIALIDADES
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM INSTRUCTORES WHERE id_especialidad = :OLD.id_especialidad;

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20002,
            'No se puede eliminar la especialidad: tiene ' ||
            v_count || ' instructor(es) asignado(s).');
    END IF;
END;
/


-- ● Valida conflicto de horario al insertar cita
CREATE OR REPLACE TRIGGER TRG_CITAS_BI
BEFORE INSERT ON CITAS
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM CITAS
    WHERE id_instructor = :NEW.id_instructor
      AND fecha = :NEW.fecha
      AND hora = :NEW.hora
      AND estado NOT IN ('CANCELADA', 'COMPLETADA');

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20003,
            'El instructor ya tiene una cita programada en esa fecha y hora.');
    END IF;
END;
/


-- ● Protege borrado de planes con membresias activas
CREATE OR REPLACE TRIGGER TRG_PLANES_MEMBRESIAS_BD
BEFORE DELETE ON PLANES_MEMBRESIAS
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM MEMBRESIAS
    WHERE id_plan = :OLD.id_plan AND estado = 'ACTIVA';

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20004,
            'No se puede eliminar el plan: hay ' ||
            v_count || ' membresia(s) activa(s) asociada(s).');
    END IF;
END;
/


-- ● Al desactivar usuario, cascada a membresias
CREATE OR REPLACE TRIGGER TRG_USUARIOS_BU
BEFORE UPDATE OF estado ON USUARIOS
FOR EACH ROW
WHEN (NEW.estado IN ('INACTIVO', 'SUSPENDIDO', 'BLOQUEADO')
      AND OLD.estado NOT IN ('INACTIVO', 'SUSPENDIDO', 'BLOQUEADO'))
BEGIN
    UPDATE HISTORIAL_MEMBRESIAS
    SET activa = 0, fecha_fin = SYSDATE
    WHERE id_cliente = :OLD.numero_identificacion AND activa = 1;
END;
/


-- ============================================================
--  7. DATOS INICIALES
-- ============================================================

-- Especialidades por defecto (solo si la tabla esta vacia)
-- NOTA: Se omite columna identity (BY DEFAULT o ALWAYS) para evitar ORA-32795
INSERT INTO ESPECIALIDADES (nombre)
SELECT 'ENTRENADOR PERSONAL' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ESPECIALIDADES WHERE nombre = 'ENTRENADOR PERSONAL');
INSERT INTO ESPECIALIDADES (nombre)
SELECT 'NUTRICION'           FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ESPECIALIDADES WHERE nombre = 'NUTRICION');
INSERT INTO ESPECIALIDADES (nombre)
SELECT 'FISIOTERAPIA'        FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ESPECIALIDADES WHERE nombre = 'FISIOTERAPIA');
INSERT INTO ESPECIALIDADES (nombre)
SELECT 'YOGA / PILATES'      FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ESPECIALIDADES WHERE nombre = 'YOGA / PILATES');
INSERT INTO ESPECIALIDADES (nombre)
SELECT 'CARDIO'              FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM ESPECIALIDADES WHERE nombre = 'CARDIO');

-- Planes por defecto (sin columna identity)
INSERT INTO PLANES_MEMBRESIAS (nombre, descripcion, precio_mensual, precio_semestral, precio_anual)
SELECT 'BASICO',  'Acceso a sala de pesas y cardio', 120000, 600000, 1080000
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PLANES_MEMBRESIAS WHERE nombre = 'BASICO');
INSERT INTO PLANES_MEMBRESIAS (nombre, descripcion, precio_mensual, precio_semestral, precio_anual)
SELECT 'ESTANDAR','Sala + clases grupales + 2 sesiones con instructor', 180000, 900000, 1620000
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PLANES_MEMBRESIAS WHERE nombre = 'ESTANDAR');
INSERT INTO PLANES_MEMBRESIAS (nombre, descripcion, precio_mensual, precio_semestral, precio_anual)
SELECT 'PREMIUM', 'Acceso completo + instructor personal + nutricion', 280000, 1400000, 2520000
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PLANES_MEMBRESIAS WHERE nombre = 'PREMIUM');

-- Cliente de prueba para el chatbot (GymbroAI usa ID 123456)
INSERT INTO USUARIOS (numero_identificacion, tipo_identificacion, nombre, apellidos, telefono, correo, contrasena_hash, estado, fecha_registro, tipo_usuario)
SELECT '123456', 'CC', 'Cliente', 'Prueba', '3001234567', 'cliente.prueba@email.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'ACTIVO', SYSDATE, 'CLIENTE'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM USUARIOS WHERE numero_identificacion = '123456');

INSERT INTO CLIENTES (numero_identificacion, direccion, fecha_nacimiento)
SELECT '123456', 'Calle 1 # 2-3, Valledupar', TO_DATE('1995-06-15', 'YYYY-MM-DD')
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM CLIENTES WHERE numero_identificacion = '123456');

COMMIT;


-- ============================================================
--  8. VERIFICACION (opcional, comentar si no se desea ver)
-- ============================================================

-- Correccion FK: SESIONES_GYMBROT → USUARIOS (no solo CLIENTES)
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SESIONES_GYMBROT DROP CONSTRAINT fk_ses_cliente';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
ALTER TABLE SESIONES_GYMBROT ADD CONSTRAINT fk_ses_usuario
    FOREIGN KEY (id_cliente) REFERENCES USUARIOS(numero_identificacion);

SELECT 'TABLAS CREADAS/CORREGIDAS CORRECTAMENTE' AS estado FROM DUAL;


-- ====================================================================
--  FIN DEL SCRIPT
-- ====================================================================
